### ISSUE TITLE
Tech feedback on settings page design

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#137]
Here is the first mock of the Settings page. There are multiple ways to design a page like this so I'm curious -- does this design interaction (sliders) make sense from your perspective? Are there technical constraints that might make this overly complicated?

(note, this question is separate from any around priority order of the elements on this page)

Some details:

- Sliders: only plus/minus need to work with tactile pad but touch screen would be actual slider.
- Audio speed: VVSG suggests 6 settings from 50wpm to 300wpm, with the default at 125-150 wpm (this is based on using text to speech, but we are, so it should be fine.
- Audio volume: VVSG has an 80DB SPL range 20-100) and says increments should be 10db, with the default at 70
- TBD if "cancel" should be changed to "reset"
- TBD if this is too much (from a user perspective) to have on 1 page but we're going to start with it on one page and see.

![image](https://user-images.githubusercontent.com/38819292/54705380-0dd47500-4b13-11e9-91d9-d4935a893b16.png)

**Comment by beausmith** [comment]
Thanks for posting @suzannechapman!

Having all settings on one screen certainly keeps the design simple, intuitive, and obvious. So much so that there is no need for additional "help" text!  🙌 

## ⚙️ Technical Feedback (to your questions)

### Does this design interaction (sliders) make sense from your perspective?
Range inputs (sliders) will work just fine. 

We can implement changes via:
- click on +/- buttons
- click on steps
- drag between steps

### Are there technical constraints that might make this overly complicated?
I do not believe it is technically possible to adjust the system audio volume or ChromeVox’s "rate of speech" from within the web app. The ChromeVox extension does have keyboard shortcuts to adjust the "rate of Speech" if the voter has keyboard access. The ChromeVox extension also has an unmapped shortcut for "speech volume" but (oddly) I am unable to map a keyboard shortcut for this setting.

## 🤔 Other Feedback, Questions, Ideas 💡
- Why are the section headings so small / same size as body copy?
- Why are the titles indented from the left margin differently than the screen title?
- Why is the horizontal separator different between "Audio volume" and "Audio speed"? Perhaps more white-space between them might help?
- What does this Settings screen look like at smallest text size? and at largest text size?
- Which of the contrast settings is currently selected? What do the un/selected contrast buttons states look like?
- What does the Settings screen look like when each of the contrast settings are applied?
- How does this work when on a smaller screen? When there are more settings or less settings based upon particular electoral district requirements? I would assume:
    - Modal goes full screen.
    - Main actions anchored to bottom of screen.
    - Main content scrolls up and down when content is larger than container. Or settings needs to be smaller to accommodate additional settings without scrolling?
- Our current implementation has a "Clear Selections". How would you add this setting to this screen?
- Where is the language setting? You previously stated that it would be both in the settings screen and available in the language screen. Will people get confused if there are settings which are not on the settings screen?
- How does this screen look when when there is 1, 2, or more languages?
- What is the order of the settings based upon?
- How does the screen/design change when clicking a different text size or contrast setting? I would assume that the UI changes to reflect the selected choice?
- Does clicking "Cancel" return the settings to what they were before changing anything?
- If we use the label "Reset" instead of "Cancel", does this imply reset to "default settings" or revert to the settings as they were before the Settings modal was opened? Some options in order of simplicity:
    1. Changing any setting actually applied that setting, there is no need for a second action to apply settings. Use a single action button, "Close" which simply closes the modal. (Potentially there could be a separate setting to "restore default settings" somewhere in the settings screen.)
    2. Changing any setting actually applies that setting, there is no need for a second action to apply settings. Use two action buttons, "Cancel" and "Apply" which respectively return to settings before window opened, or use the setting as they have been changed.
    3. Other more complicated solutions?

**Comment by suzannechapman** [comment]
Excellent questions. This was a first draft design so some of those details were waiting to make sure we're on the right path but this will make a short job of sorting out the next version :) 

Re: rate of speech, we should probably discuss as a group to figure out what plan B looks like 

Re: language settings, the current plan is to only offer language on it's own separate page (not this one). We may decide we need a path from this settings page to the language page. TBD. 

Re: what it looks like with enlarged text, we've intentionally not been mocking these types of variations during the initial design stage but would that be useful in this case? Other screens too?

**Comment by beausmith** [comment]
> Re: what it looks like with enlarged text, we've intentionally not been mocking these types of variations during the initial design stage but would that be useful in this case? Other screens too?

My current task is [Settings: font-sizes](https://github.com/votingworks/bmd/issues/121), so I'm moving forward and will have something to show soon. At this point I think it makes more sense to iterate in code so we can test drive and get a real feel for the product in its native interactive medium.

**Comment by beausmith** [comment]
I'm gonna close this issue as I believe it is complete. If additional tech feedback is needed, please feel free to reopen with questions, etc. 😸
