### ISSUE TITLE
Remove header/footer from printed ballot

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#183]
Is it possible to remove the header/ footer on the printed ballot (ie the date, "Voting Works Ballot Marking Device", and url at the bottom)?

![image](https://user-images.githubusercontent.com/38819292/55498125-d7b5eb80-5610-11e9-87b3-1e262412aee1.png)

**Comment by beausmith** [comment]
This issue is related to a missed setup step.

See instructions on the Setting up BMD Hardware screen for [Setup and Install Brother HL-L2300D Printer](https://github.com/votingworks/bmd/blob/master/docs/hardware.md#setup-and-install-brother-hl-l2300d-printer).

Missing steps:

- Open browser, go to random web page, and select print (or Ctrl-P).
- Select "More settings", then change "Margins" to "None".
