### ISSUE TITLE
Fix: write-in option disappears once you select max candidates

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#188]
On contests with a write-in option, once you select the max candidates, the option to do a write-in disappears.

**Comment by beausmith** [comment]
On candidate contests, the write-in option does disappear once the voter selects max number candidates.

If another behavior is expected, please re-open issue and add clarification.

**Comment by whitneyq** [comment]
So, it reappears when if a candidate is deselected so there is again a possible selection to be made, so that's good, but it's a little distracting to see a candidate block appear and disappear. 

What's your thought about why it's important to hide it?

**Comment by beausmith** [comment]
Given the title and first comment of this issue, is unclear what the expected behavior is.

Once max votes have been reached in a contest, what should happen to the non-selected options? 

The non-selected options can be removed, disabled (greyed-out, etc), or they can remain exactly the same.

**Comment by whitneyq** [comment]
I don't know that we had expected behaviors, but thought it was a little startling to see the write-in disappear. 

In general, non-selected options should never disappear. Because they are still available, albeit after deselecting one other.  The critical scenario is this:

- Voter enters contest, selects a likely candidate
- Then, peruses other candidates while reaching for the Next Contest button, and notices that it wasn't Joe Smith they meant to vote for, but Some Other Candidate. 
- Seeing that name lets them change their selection to the candidate they now really want.

In general, there's such a strong advantage to being top of ticket - its why ballot order is always set by law in some way - that hiding a candidate lower down the list just Isn't Done. 

I have seen a voting system that greyed the other candidates, so there was a visible change, but left them active. The mixed messages were a little confusing, and my thought after watching voters encounter it was that it wasn't worth it. 

My worry about removing the write-in is that
- someone notices something disappearing without actually seeing what really happened and cries "It's changing my options"
- the write-in option is still valid, just no more available than any other at that moment.

I'd take the simpler course and just leave it all alone.

See what I mean?
