### ISSUE TITLE
Make focus outline more noticable

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#190]
If it's super easy to do.... this will help with testing the XAC navigation.

**Comment by whitneyq** [comment]
Let us know when we can see the fix.

Weighing in now with a bit more info: 
When we were working with the switches with Denis it was almost impossible to see unless you put your face at the side of the screen.

This highlight only needs to appear with switch/keyboard navigation (because the alternative is to just touch the thing you want to activate), but is has to be:
- Big enough to see easily
- Visible on both the contests and top/bottom menu buttons

Remember that people using the switches are often sitting farther away from the screen than normal because of their posture in a wheelchair.

Also remember that the lighting in polling places is often glare-y and over bright, so the focus highlight needs to compensate for this.

IMHO - this is something that will affect testing with the XAC on May 3.
