### ISSUE TITLE
Notes from meeting with Noel on 2019-04-16

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#245]
# Notes from Noel visit 2019-04-16

## Possible Action Items
- screen reader: simplify to necessary vs optional info
- should not have any "html" voice. All UI should be voting specific.
- need physical controllers for speech speed and volume.
- Button aria label: "press select to go to next contest"
- How does BMD get activated? Poll worker scans QR code.
- Add precinct number/name? too much info or necessary?
- View VO text specified in VSAP system.
- button to reset focus to start of page, "Where am i?"
- voter needs closure on every single action. data-attributes for text to read if user clicks button in various conditions.
- screen to explore keyboard - ask Noel for best practices on this screen.
- Research time between page load and first text speech.
- Audio indicator for button press and contest advance

## Beau Raw Notes
- Round edges - sharp edges are offensive to visually impaired.
- Braille labels - No braille in the strike area.
- Navigation Cross

**Start Screen**
- Too much info is also not helpful.
- simply "2020 Election" is acceptable
- How to indicate "button"
- Add summary, then advise how to proceed.
- Add precinct, 
- UI can command vs invite.
- Tap the next button to start voting.
- closure on every single action.
- add keyboard explore menu (accessibility screen)
- many may start at slow speed setting, then speed up as they get through.
- volume needs to be adjusted on the fly to match ambient noise.
- should be tactile controls for volume and rate. 
- to start voting, press the X button.
- Command, vs opportunity/invitation. 
- Feedback on all control presses.

**Candidate Contest**
- seems to be long time between page load and first text speech.
- provide intro to the page with instructions, then pause until I advance focus.
- would prefer to hear "Selected" vs "checked", Should be as voting specific as possible.
  - use buttons with updated text "Selected…"

## Ben Raw Notes
- Check-in: depends on the election official.
- Vsap poll pass
- Noel has fought with LA county about constrained OCR.
- Noel feels the whole way through. Corners of controllers can hurt. Too sharp on Xbox adaptive controller. Braille labels.
- Noel likes vsap keypad design. California law requires pause key. Noel doesn't think it's a good idea for this.
- Los Angeles is not gonna right es&s patent, redesigned the keypad.
- “Where are earphones?”
- Extra buttons on controller are confusing. Directional are too small. Rocker not clear. Left hand directional is weird. 
- Need Braille labeling for buttons. But only 10% use it.
- Directional should be shaped like arrows.
- Need separate speaker for reset and what not.
- Sound indicators when going to next screens.
- “Get started” means what?
- Too much text on intro screen. Audio needs to start with most important information. “Does voter need to know?”
- This shouldn't work like a computer, it shouldn't have extraneous information. User information should be very specific.
- Where is language selection?
- Don't want to read the whole screen
- Start screen: precinct number, not date.
- “To start voting, tap the next key.”
- There should be closure on every action. Button press should do something.
- People may need to change volume and speed at middle of it. 
- Volume should restart with every session.
- Inclusive and other manufacturers that make controllers.
- Don't assume user knows “button”
- Watch long delays.
- Pregnant delays. :(
- Faster response. At least a click.
- Don't read the whole page.
- List number of candidates.
- For 2 button controller, maybe show the list of contests first. 
- Voting specific terminology only.
- What happens when voter is lost?

**Comment by beausmith** [comment]
Documenting as issue for future reference.

**Comment by whitneyq** [comment]
Add precinct number/name? too much info or necessary?
 - Necessary. It's both a point of complete information and a potential hack to change contests. 

Should not have any "html" voice. All UI should be voting specific.
- Agree. This is the difference between a general screen reader and a ballot marking device voice, which is used by many different people who have different needs.

How does BMD get activated? Poll worker scans QR code.
- Anyone can scan the QR code if it's set up right, but poll worker assistance should be available for all voters. 

Audio indicator for button press and contest advance
- Agree, let's talk about how this happens, because it's useful for people not using the audio as well. (And that it's lower priority)

Research time between page load and first text speech.
- Good opportunity for a "working" earcon. 

Voter needs closure on every single action. data-attributes for text to read if user clicks button in various conditions.
- We have been working on spec'ng this.

Button aria label: "press select to go to next contest"
- Is this just an example of what the button would read? Best practice is "Go to next contest" without repeating the instructions. And, people using the 5-button interface would press the right arrow.

Buttons suggestions:
There's lots of desire for physical buttons for things that are good to want, but I'd have to say that the more buttons we saw on a voting system controller, the more difficulty a range of users had with it. Volume and play/pause were easy to teach, but on systems that had a special button to restart a contest, no one ever found them, even when they had heard them in the opening instructions. By the time they needed them, they had forgotten. I was sad about this, but it's what happened. 

A lot of this hinges on how much we can control ChomeVox.
