### ISSUE TITLE
Vote count line should be more useful.

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#316]
- add # of candidates
- you may choose N more. (when N is Seats - 1)

## Possible Solution
- **0 selected** - You may vote for 4 of 13 candidates.
- **N selected** - You may vote for 1 of 4 candidates.
- **Max selected** - You have voted for 4 of 4 candidates. 
(Not ideal because the "of candidates" changes.)

**Comment by whitneyq** [comment]
Our solution in Anywhere Ballot was tested pretty extensively, so might be a starting point

First, the countdown was used ONLY for multi-select contests. 

- If no selections have been made:
        Vote for N   [ or some jurisdictions require "Vote for up to N"]

- Countdown begins with first selection, for example
       Vote for 3. 
       Vote for 3. You can choose **2** more.    [ with the number in bold/red]
       Vote for 3. You can choose **1** more.
       Vote for 3. You can choose **0** more.


In testing was better to count down how many selections were left than count up how many were already made, because it was a clearer, positive instruction and didn't force users into (minor) arithmetic. This was especially important for users with low reading and civic literacy.

There's a simple way to include this information in audio, too.

**Comment by beausmith** [comment]
@whitneyq - Thanks for this. Very useful.

**Comment by benadida** [comment]
Agree, let's make it better, @beausmith you make the call.

**Comment by beausmith** [comment]
Implementing this solution:
- **Vote for 4.**
- Vote for 4. **You may select 3 more.**
- Vote for 4. **You may select 2 more.**
- Vote for 4. **You may select 1 more.**
- Vote for 4. **You have selected 4.**
