### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#336]
## Problem
- If voter uses multi-touch to zoom, they may not be able to zoom out.
- BMD could be considered "broken" if it is "stuck" in a zoomed in state. 

## Solution
- Typically disabling zoom is considered anti-accessibility for voters with poor sight. Because we have font-size settings, perhaps disabling zoom is acceptable.

## Implementation
- [x] Via css: `html { touch-action: none; }`
- [x] Disable zoom with Chrome kiosk flags (https://stackoverflow.com/a/23057591/101290) using:

      chrome.exe --kiosk --incognito --disable-pinch --overscroll-history-navigation=0

  - `--disable-pinch` - disables the pinch-to-zoom functionality
  - `--overscroll-history-navigation=0` - disables the swipe-to-navigate functionality

**Comment by whitneyq** [comment]
No voting system that I know of uses screen zoom, using a responsive-like solution and the font-size settings instead. 

VVSG and VVSG 2.0 requirements assume that text size settings control the scaling:
7.1-H – Scaling and zooming (electronic display)
When the text size is changed, all other information in the interface, including informational icons, screen titles, buttons, and ballot marking target areas, must change size to maintain a consistent relationship to the size of the text. Informational elements in the interface do not have to be scaled beyond the size of the text.
1.	When the text is enlarged up to 200% (or 7.1 mm text size), the ballot layout must adjust so that there is no horizontal scrolling or panning of the screen.  
2.	When the text is enlarged more than 200%, there may be horizontal scrolling or panning if needed to maintain the layout of the ballot and a consistent relationship between the text for ballot options and associated marking targets.

Discussion 
The intention of this requirement is that all of the informational elements of the interface change size in response to the text size. However, some interface designs include elements that are already large enough that making them larger would distort the layout. In this case, this does not require those elements to grow proportionately beyond the size of the text.
Techniques for managing scaling and zooming an electronic interface while adjusting the layout to fit the new size are sometimes called responsive design or responsive programming.
This requirement does not preclude novel approaches to on-screen magnification such a zoom lens showing an enlarged view of part of a screen (as long as it meets the requirements in 7.2 for the operability of the controls).
This requirement follows WCAG 2.0 in requiring scaling with no horizontal scrolling up to 200% and allowing zooming with horizontal scrolling for larger text.

**Comment by beausmith** [comment]
👍
